version: 1.0.{build}

platform: Any CPU

nuget:

  account_feed: true

build:

  publish_nuget: true

  publish_nuget_symbols: true

  include_nuget_references: true

  verbosity: minimal

build_script:
- cmd: >-
    cd C:\projects\split-post-commit-hook-svn-git-hg\build

    mkdir msvc

    copy spch.nuspec msvc

    cd msvc

    cmake -G"Visual Studio 14" -DCMAKE_BUILD_TYPE=Release ..

    cmake --build . --config Release

    dir /p ..\bin

    cd ..\bin\Release

    dir /p >spch.build.list

    spch.exe -h

    spch.exe -i

