version: 1.0.{build}
build_script:
- cmd: >-
    cd C:\projects\split-post-commit-hook-svn-git-hg

    mkdir /p msvc

    cd msvc

    cmake -G"Visual Studio 14" -DCMAKE_BUILD_TYPE=Debug ..

    cmake --build . --config %CMAKE_BUILD_TYPE%

    cd ../bin/Debug

    spch.exe -h

    spch.exe -i

